function combinedMask = getMask_GRAB( trials, fieldNames, recordingSite )
% % MP_get_psth %
%PURPOSE:   Get trial mask defined by conjunction of unlimited trial conditions
%AUTHORS:   MJ Siniscalchi, 170113
%
%INPUT ARGUMENTS
%   trials:         structure generated by flex_getTrialMask()
%   fieldNames:     the field names involved
%
%OUTPUT ARGUMENTS
%   combinedMask:   mask where all fields are satisfied, i.e. an AND operation

temp = [];
for i = 1:length(fieldNames) 
        if strcmp(fieldNames{i},'contra')
            if strcmp(recordingSite,'left')
                newfieldNames{i} = 'right';
                temp = [temp trials.(newfieldNames{i})];
            else
                newfieldNames{i} = 'left';
                temp = [temp trials.(newfieldNames{i})];
            end
        elseif strcmp(fieldNames{i},'ipsi')
            if strcmp(recordingSite,'left')
                newfieldNames{i} = 'left';
                temp = [temp trials.(newfieldNames{i})];
            else
                newfieldNames{i} = 'right';
                temp = [temp trials.(newfieldNames{i})];
            end
        elseif strcmp(fieldNames{i}, 'miss early')
            tempMiss = trials.miss;
            tempMiss(end-49,end) = 0; % only consider early missed trials
            temp = [temp tempMiss];
        elseif strcmp(fieldNames{i}, 'miss late')
            tempMiss = trials.miss;
            tempMiss(1:end-50) = 0;  % only consider late missed trials
            temp = [temp tempMiss];
        else
            newfieldNames{i} = fieldNames{i};
            temp = [temp trials.(newfieldNames{i})];
        end
     %trialMasks as columns of array
end
combinedMask = all(temp,2); %true if all elements are non-zero

end

