function plot_signficance(input,t, tlabel,xtitle,colorRange,savefigpath)
% % plot_selectivity %
%PURPOSE:   Plot signficance based on linear regressions
%AUTHORS:   AC Kwan 170515
%
%INPUT ARGUMENTS
%   input:       Structure generated by calc_selectivity()
%   sortParam:
%       if #values = 2, e.g. [1 3], then sort the cells based on selectivity value in this time period
%       if #values = number of cells, e.g. [1 3 4 2 5], then sort the cells directly based on this ordering
%   tlabel:       Text to put as title of the plot.
%   xtitle:       Text to put as the label for x-axis.
%   colorRange:   Max and min values that define the range of the color scale
%
%OUTPUT ARGUMENTS
%   cellOrder:    Sorting order of the cells
%                 (could be fed back as input 'sortParam' for next call of
%                 this function)

%% Plotting parameters

colors=cbrewer('seq','Reds',256);
colors=flipud(colors);
colorRange = [0 0.01];

%% Setup

nCells = size(input,1)*size(input,2);
pref=[];
for j=1:size(input,1)
    for tt = 1:size(input,2)
        ind = (j-1)*size(input,1) + tt;
        pref(ind,:)=input(j,tt,:);
    end
end

%%
figure;


   
   


%plot in pseudocolor
subplot(1,3,1);
image(t,1:nCells,pref,'CDataMapping','scaled');
hold on; plot([0 0],[0 nCells+1],'w');
colormap(colors);
caxis([colorRange(1) colorRange(2)]);      %normalize dF/F heatmap to max of all conditions
ylabel('Cells');
xlabel(xtitle);
title(tlabel);

%make a color scale bar
subplot(3,20,60);
image(0,linspace(colorRange(1),colorRange(2),100),linspace(colorRange(1),colorRange(2),100)','CDataMapping','scaled');
colormap(colors);
caxis([colorRange(1) colorRange(2)]);
title(['p value']);
set(gca,'YDir','normal');
set(gca,'XTick',[]);

print(gcf,'-dpng',fullfile(savefigpath,[tlabel,' norm']));
            saveas(gcf, fullfile(savefigpath,[tlabel,' norm']), 'fig');
            saveas(gcf, fullfile(savefigpath,[tlabel,' norm']), 'svg');

            close

end